
# Model args
hidden_dim: 64
activation: tanh
norm_obs: false
norm_reward: false
clip_obs: 10
clip_reward: 10

# actor config
actor_config:
  policy_type: objective_softmax
  beta_init: 1.0

# Loss args
gamma: 0.99
use_gae: true
gae_lambda: 0.95
use_clipped_value: false
clip_param: 0.2
target_kl: 0.01
entropy_coef: 0.01
value_coef: 0.5

# Optim args
opt_epochs: 10
mini_batch_size: 64
actor_lr: 0.001
critic_lr: 0.001
max_grad_norm: 0.5

# Runner args
max_env_steps: 1000000
num_workers: 1
rollout_batch_size: 1
rollout_steps: 100
deque_size: 10
eval_batch_size: 10

# Misc
log_interval: 0
save_interval: 0
num_checkpoints: 0
eval_interval: 0
eval_save_best: false
tensorboard: false

